backend:
  name: git-gateway
  branch: main

local_backend: true
media_folder: static/img/common
public_folder: /img/common
slug:
  encoding: "ascii"
  clean_accents: true
locale: 'pl'
editor:
  preview: false

collections:
  - name: 'pages'
    label: 'Strony'
    files:
    - name: 'history'
      label: 'Historia'
      file: 'content/history/2023-06-27T21:37:09Z_historia.md'
      media_folder: 'images'
      public_folder: 'images'
      format: 'frontmatter'
      fields:
        - label: "Data utworzenia"
          name: "date"
          widget: "datetime"
          date_format: "DD.MM.YYYY"
          time_format: "HH:mm"
        - {label: "Nazwa", name: "title", widget: "string"}
        - {label: "Treść", name: "body", widget: "markdown"}
    - name: 'guide'
      label: 'Poradnik'
      file: 'content/guide/2023-10-04T22:19:32Z_poradnik.md'
      media_folder: 'images'
      public_folder: 'images'
      format: 'frontmatter'
      fields:
        - label: "Data utworzenia"
          name: "date"
          widget: "datetime"
          date_format: "DD.MM.YYYY"
          time_format: "HH:mm"
        - {label: "Nazwa", name: "title", widget: "string"}
        - {label: "Treść", name: "body", widget: "markdown"}
  - name: 'definitions'
    label: 'Definicje'
    folder: 'content/definitions/'
    media_folder: 'images'
    public_folder: 'images'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}T{{hour}}:{{minute}}:{{second}}Z_{{slug}}'
    fields:
      - label: "Data utworzenia"
        name: "date"
        widget: "datetime"
        date_format: "DD.MM.YYYY"
        time_format: "HH:mm"
      - label: "Slug"
        name: "slug"
        widget: "string"
        pattern: ['^[a-z0-9\-]*$', "Może zawierać tylko małe litery, cyfry i myślnik"]
        hint: "Musi być unikalne; będzie częścią adresu strony."
      - {label: "Obrazek", name: "fullPhoto", widget: "image", required: false}
      - {label: "Nazwa", name: "title", widget: "string"}
      - {label: "Nazwa EN", name: "titleEn", widget: "string"}
      - {label: "Priorytet", name: "priority", widget: "number", default: 0, hint: "Im wyższy tym wyżej na stronie."}
      - {label: "Niepubliczne", name: "draft", widget: "boolean", default: true}
      - {label: "Treść", name: "body", widget: "markdown"}
  - name: 'stories'
    label: 'Opowieści'
    folder: 'content/stories/'
    media_folder: 'images'
    public_folder: 'images'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}T{{hour}}:{{minute}}:{{second}}Z_{{slug}}'
    fields:
      - label: "Data utworzenia"
        name: "date"
        widget: "datetime"
        date_format: "DD.MM.YYYY"
        time_format: "HH:mm"
      - label: "Slug"
        name: "slug"
        widget: "string"
        pattern: ['^[a-z0-9\-]*$', "Może zawierać tylko małe litery, cyfry i myślnik"]
        hint: "Musi być unikalne; będzie częścią adresu strony."
      - {label: "Miniaturka", name: "thumbnail", widget: "image", required: false}
      - {label: "Pełne zdjęcie", name: "fullPhoto", widget: "image", required: false}
      - {label: "Imię / pseudonim", name: "title", widget: "string"}
      - label: "Definicje"
        name: "definitions"
        widget: "list"
        default: ["2023-06-27T21:37:09Z_niebinarnosc"]
        summary: "{{fields.definition}}"
        field:
          label: "Definicje"
          name: "definition"
          widget: "relation"
          collection: "definitions"
          value_field: "{{slug}}"
          search_fields: ["heading", "id", "title"]
          display_fields: ["title"]
        hint: "Powinna być co najmniej jedna."
      - label: "Triggery"
        name: "triggers"
        widget: "list"
        required: false
        summary: "{{fields.trigger}}"
        field: {label: "Trigger", name: "trigger", widget: "string"}
      - {label: "Niepubliczne", name: "draft", widget: "boolean", default: true}
      - {label: "Treść", name: "body", widget: "markdown"}
  - name: 'representation'
    label: 'Reprezentacja'
    folder: 'content/representation/'
    media_folder: 'images'
    public_folder: 'images'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}T{{hour}}:{{minute}}:{{second}}Z_{{slug}}'
    fields:
      - label: "Data utworzenia"
        name: "date"
        widget: "datetime"
        date_format: "DD.MM.YYYY"
        time_format: "HH:mm"
      - label: "Slug"
        name: "slug"
        widget: "string"
        pattern: ['^[a-z0-9\-]*$', "Może zawierać tylko małe litery, cyfry i myślnik"]
        hint: "Musi być unikalne; będzie częścią adresu strony."
      - {label: "Obrazek", name: "fullPhoto", widget: "image", required: false}
      - {label: "Nazwa", name: "title", widget: "string"}
      - label: "Osoby autorskie"
        name: "authors"
        widget: "list"
        summary: "{{fields.name}}"
        fields:
          - {label: "Nazwa", name: "name", widget: "string"}
          - {label: "Link", name: "link", widget: "string", required: false}
      - {label: "Kategoria", name: "category", widget: "select", options: ["Książka", "Komiks", "Film", "Serial", "Gra wideo", "Teatr", "Sztuka"]}
      - {label: "Rok wydania", name: "year", widget: "number", required: false}
      - {label: "Ograniczenie wiekowe", name: "ageLimit", widget: "number", required: false}
      - {label: "Opis fabuły", name: "storyDescription", widget: "text"}
      - {label: "Opis reprezentacji", name: "representationDescription", widget: "text"}
      - {label: "Niepubliczne", name: "draft", widget: "boolean", default: true}